export const LOCATION_INFO = [
    {
        type: 'office',
        name: 'Shanghai',
        x: 1612,
        y: 737,
        namePosition: 'right',
    },
    {
        type: 'office',
        name: 'Hangzhou',
        x: 1591,
        y: 754,
        namePosition: 'left',
    },
    {
        type: 'office',
        name: 'Singapore',
        x: 1563,
        y: 905,
        namePosition: 'right',
    },
    {
        type: 'remote',
        name: 'Berkeley,CA',
        x: 267,
        y: 651,
        namePosition: 'left',
    },
    {
        type: 'remote',
        name: 'Los Angeles,CA',
        x: 295,
        y: 714,
        namePosition: 'left',
    },
    {
        type: 'remote',
        name: 'Charpel Hill,NC',
        x: 519,
        y: 623,
        namePosition: 'right',
    },
    {
        type: 'remote',
        name: 'Penang',
        x: 1489,
        y: 865,
        namePosition: 'left',
    },
    {
        type: 'remote',
        name: 'Tokyo',
        x: 1706,
        y: 672,
        namePosition: 'right',
    },
    {
        type: 'origin',
        img: require('../../assets/about/origin-poland.png'),
        name: 'Poland',
        x: 1059,
        y: 563,
        namePosition: 'right',
    },
    {
        type: 'origin',
        img: require('../../assets/about/origin-rwanda.png'),
        name: 'Rwanda',
        x: 1099,
        y: 900,
        namePosition: 'right',
    },
    {
        type: 'origin',
        img: require('../../assets/about/origin-china.png'),
        name: 'China',
        x: 1400,
        y: 700,
        namePosition: 'right',
    },
    {
        type: 'origin',
        img: require('../../assets/about/origin-korea.png'),
        name: 'Korea',
        x: 1625,
        y: 695,
        namePosition: 'left',
    },
    {
        type: 'origin',
        img: require('../../assets/about/origin-japan.png'),
        name: 'Japan',
        x: 1714,
        y: 624,
        namePosition: 'none',
    },
    {
        type: 'origin',
        img: require('../../assets/about/origin-penang.png'),
        name: 'Penang',
        x: 1510,
        y: 850,
        namePosition: 'none',
    },
    {
        type: 'origin',
        img: require('../../assets/about/origin-singapore.png'),
        name: 'Singapore',
        x: 1520,
        y: 893,
        namePosition: 'none',
    },
    {
        type: 'origin',
        img: require('../../assets/about/origin-hongkong.png'),
        name: 'Hongkong',
        x: 1558,
        y: 788,
        namePosition: 'right',
    },
];
