name: S3 Sync

on:
  push:
    branches: [ "main" ]
    paths: [ "public/files/**" ]

jobs:
  s3-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-southeast-1'
        SOURCE_DIR: 'public/files'
        DEST_DIR: 'landing/files'
